name: flutter_painter
version: 2.0.0
description: A Flutter widget to draw scribbles, text, shapes and images on a background image or color
homepage: https://github.com/omarhurani/flutter_painter
repository: https://github.com/omarhurani/flutter_painter
issue_tracker: https://github.com/omarhurani/flutter_painter/issues

environment:
  sdk: ^3.4.4
  flutter: ">=3.22.3"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.18.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4

flutter:
